/**
 * Font to Base64 Converter
 * 
 * This script converts font files to Base64 strings for embedding in CSS.
 * This ensures fonts are always available when Puppeteer generates PDFs,
 * even in Docker, CI, or serverless environments.
 * 
 * Usage:
 *   node tools/convert-font.js
 * 
 * Output:
 *   - Generates src/styles/embedded-fonts.css with @font-face rules
 *   - All fonts are embedded as Base64 data URIs
 */

const fs = require('fs');
const path = require('path');

// Configuration: Define your fonts here
const FONTS = [
  {
    family: 'Inter',
    weight: 300,
    style: 'normal',
    file: './public/fonts/Inter-Light.ttf',
    format: 'truetype'
  },
  {
    family: 'Inter',
    weight: 400,
    style: 'normal',
    file: './public/fonts/Inter-Regular.ttf',
    format: 'truetype'
  },
  {
    family: 'Inter',
    weight: 500,
    style: 'normal',
    file: './public/fonts/Inter-Medium.ttf',
    format: 'truetype'
  },
  {
    family: 'Inter',
    weight: 600,
    style: 'normal',
    file: './public/fonts/Inter-SemiBold.ttf',
    format: 'truetype'
  },
  {
    family: 'Inter',
    weight: 700,
    style: 'normal',
    file: './public/fonts/Inter-Bold.ttf',
    format: 'truetype'
  },
];

// Output file path
const OUTPUT_FILE = './src/styles/embedded-fonts.css';

/**
 * Convert a font file to Base64 string
 * @param {string} filePath - Path to font file
 * @returns {string} Base64 encoded string
 */
function convertFontToBase64(filePath) {
  try {
    const fontBuffer = fs.readFileSync(filePath);
    return fontBuffer.toString('base64');
  } catch (error) {
    console.error(`❌ Error reading font file: ${filePath}`);
    throw error;
  }
}

/**
 * Get MIME type based on font format
 * @param {string} format - Font format (truetype, woff, woff2, etc.)
 * @returns {string} MIME type
 */
function getMimeType(format) {
  const mimeTypes = {
    'truetype': 'font/ttf',
    'woff': 'font/woff',
    'woff2': 'font/woff2',
    'opentype': 'font/otf'
  };
  return mimeTypes[format] || 'font/ttf';
}

/**
 * Generate @font-face CSS rule with embedded Base64 font
 * @param {Object} font - Font configuration object
 * @returns {string} CSS @font-face rule
 */
function generateFontFace(font) {
  console.log(`📦 Converting: ${font.file}...`);
  
  // Check if file exists
  if (!fs.existsSync(font.file)) {
    console.warn(`⚠️  Font file not found: ${font.file} - Skipping...`);
    return `/* Font not found: ${font.file} */\n`;
  }

  // Convert font to Base64
  const base64Font = convertFontToBase64(font.file);
  const mimeType = getMimeType(font.format);
  const fileSize = (base64Font.length / 1024).toFixed(2);

  console.log(`   ✅ Converted: ${fileSize} KB (Base64)`);

  // Generate CSS
  return `
/* ${font.family} ${font.weight} ${font.style} - ${fileSize} KB */
@font-face {
  font-family: "${font.family}";
  src: url("data:${mimeType};base64,${base64Font}") format("${font.format}");
  font-weight: ${font.weight};
  font-style: ${font.style};
  font-display: block;
}
`;
}

/**
 * Main function to generate embedded fonts CSS
 */
function generateEmbeddedFontsCSS() {
  console.log('\n🎨 Font to Base64 Converter\n');
  console.log('─'.repeat(50));

  // Generate CSS header
  let css = `/**
 * Embedded Fonts CSS
 * 
 * This file contains all fonts embedded as Base64 data URIs.
 * Generated by: tools/convert-font.js
 * Generated at: ${new Date().toISOString()}
 * 
 * ⚠️  Do NOT edit this file manually!
 * Run "node tools/convert-font.js" to regenerate.
 * 
 * These fonts are embedded to ensure 100% reliability when:
 * - Generating PDFs with Puppeteer
 * - Running in Docker containers
 * - Running in CI/CD pipelines
 * - Running in serverless environments (Vercel, AWS Lambda, etc.)
 */

`;

  // Generate @font-face rules for each font
  let successCount = 0;
  let skipCount = 0;

  FONTS.forEach((font) => {
    const fontFace = generateFontFace(font);
    css += fontFace;
    
    if (fontFace.includes('Font not found')) {
      skipCount++;
    } else {
      successCount++;
    }
  });

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write to file
  fs.writeFileSync(OUTPUT_FILE, css, 'utf8');

  console.log('─'.repeat(50));
  console.log(`\n✅ Successfully converted: ${successCount} fonts`);
  if (skipCount > 0) {
    console.log(`⚠️  Skipped: ${skipCount} fonts (not found)`);
  }
  console.log(`📄 Output file: ${OUTPUT_FILE}`);
  
  const totalSize = (css.length / 1024).toFixed(2);
  console.log(`📊 Total CSS size: ${totalSize} KB\n`);

  // Print usage instructions
  console.log('📚 Next steps:');
  console.log('   1. Import this CSS in your Puppeteer HTML template');
  console.log('   2. Use font-family: "Inter" in your styles');
  console.log('   3. Generate PDF with Puppeteer\n');
}

// Run the script
try {
  generateEmbeddedFontsCSS();
} catch (error) {
  console.error('\n❌ Error generating embedded fonts CSS:', error.message);
  process.exit(1);
}
